config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passing_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/passing_test.rb
# frozen_string_literal: true

class PassingTest < ApplicationRecord
  SUCCESS_POINT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_answers += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def correct_answers_percent
    (correct_answers.to_f / test.questions.count.to_f) * 100
  end

  def successfully_completed?
    correct_answers_percent >= SUCCESS_POINT
  end



  def remaining_seconds
    ((created_at + test.timer.minutes) - Time.current).to_i
  end

  def time_out?
    remaining_seconds <= 0 if timer_test?
  end

  private

  def timer_test?
    test.timer.present?
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end


  def correct_answer?(answer_ids)
    return false unless answer_ids
    correct_answers_count = true_answers.count
    (correct_answers_count == answer_ids.count) && correct_answers_count == true_answers.where(id: answer_ids).count
  end

  def true_answers
    @true_answers ||= current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/controllers/passing_tests_controller.rb
class PassingTestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_passing_test, only: %i[show result update gist]
  before_action :check_time_left, only: :update

  def show

  end

  def result

  end

  def update
    @passing_test.accept!(params[:answer_ids])
    if @passing_test.completed?
      TestsMailer.completed_test(@passing_test).deliver_now
      redirect_to result_passing_test_path(@passing_test)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@passing_test.current_question)
    response = service.call

    gist_url = response.html_url
    gist_link = view_context.link_to(gist_url, gist_url, target: :blank)

    flash_option = if service.status_ok?
      make_gist!(gist_url)
        { notice: t('.success', url: gist_link) }
      else
        { alert: t('.failed') }
      end
      redirect_to @passing_test, flash_option
  end

  private

  def find_passing_test
    @passing_test = PassingTest.find(params[:id])
  end

  def make_gist!(gist_url)
    current_user.gists.create(question: @passing_test.current_question, url: gist_url)
  end
end

app/helpers/passing_tests_helper.rb
module PassingTestsHelper
  def show_result_message(passing_test)
    passing_test.successfully_completed? ? t('passing_tests.result.success') : t('passing_tests.result.failed')
  end
  def result_color(passing_test)
    passing_test.successfully_completed? ? 'text-success' : 'text-danger'
  end
end

app/views/passing_tests/_progress_bar.html.erb
<div class="progress">
  <% questions_count = @passing_test.test.questions.count %>
  <% current_question_number = @passing_test.current_question ? @passing_test.current_question_number : questions_count + 1 %>
  <%= content_tag :div,
                  '',
                  class: 'progress-bar bg-success',
                  role: 'progressbar',
                  data: { questions_count: questions_count,
                          current_question_number: current_question_number } %>
</div>

app/views/passing_tests/_timer.html.erb
<%= content_tag :span, '', class: 'timer unended text-right',
                              data: { time_left:  @passing_test.remaining_seconds }
                           %>

app/views/passing_tests/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <%= render 'progress_bar' %>
    <h1 class="<%= result_color(@passing_test) %>">
      <%= t('.header', title: @passing_test.test.title) %>
      <%= show_result_message(@passing_test)%></h1><br>
    <h2><%= link_to t('.back'), tests_path %></h2>
  </div>
</div>

app/views/passing_tests/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header', test_title: @passing_test.test.title) %></h1>

    <%= render 'progress_bar' %>
    <%= render 'timer', passing_test: @passing_test %>

    <div class="row">
      <dt class="col-sm-9">
        <%= t('.questions', current_question:
          @passing_test.current_question_number, questions_count: @passing_test.test.questions.count) %>
      </dt>
      <dd class="col-sm-3">
        <%= link_to 'Gist question', gist_passing_test_path(@passing_test), method: :post %>
      </dd>
    </div>

    <div class="card">
      <div class="card-header">
        <%= @passing_test.current_question.body%>
      </div>

      <ul class="list-group list-group-flush">
        <%= form_with url: passing_test_path(@passing_test), local: true, method: :put do |form| %>
          <%= form.collection_check_boxes :answer_ids,
          @passing_test.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <li class="list-group-item">
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </li>
         <% end %>

        </ul>
        <%= form.submit t('.next'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>