config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passing_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  MAX_ANSWERS_COUNT = 4

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true

  validate :validate_max_answers_count, on: :create

  def validate_max_answers_count
    errors.add(:question, message) if question.answers.count >= MAX_ANSWERS_COUNT
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :user
  belongs_to :category, class_name: 'Category', optional: true
  has_many :users_badges
  has_many :users, through: :user_badges


  validates :title, presence: true
  validates :path, presence: true
  validates :name, :image_path, presence: true

  BADGE_NAMES = %i[success_category success_on_first_try success_all_level].freeze

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  def gist_hash_url
    url.split("/").last
  end
end

app/models/passing_test.rb
# frozen_string_literal: true

class PassingTest < ApplicationRecord
  SUCCESS_POINT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_answers += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def correct_answers_percent
    (correct_answers.to_f / test.questions.count.to_f) * 100
  end

  def successfully_completed?
    correct_answers_percent >= SUCCESS_POINT
  end



  def remaining_seconds
    ((created_at + test.timer.minutes) - Time.current).to_i
  end

  def time_out?
    remaining_seconds <= 0 if timer_test?
  end

  private

  def timer_test?
    test.timer.present?
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end


  def correct_answer?(answer_ids)
    return false unless answer_ids
    correct_answers_count = true_answers.count
    (correct_answers_count == answer_ids.count) && correct_answers_count == true_answers.where(id: answer_ids).count
  end

  def true_answers
    @true_answers ||= current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord

  belongs_to :category
  has_many :passing_tests
  has_many :users, through: :passing_tests
  has_many :questions
  belongs_to :author, class_name: 'User'

  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, presence: true, uniqueness: { scope: :level, message: 'There can be only one Test with the given name and level' }
  
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }


  def self.titles_by_category(title)
    by_category(title).order(title: :desc).pluck(:title)
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :passing_tests
  has_many :tests, through: :passing_tests
  has_many :tests_author, class_name: 'Test', foreign_key: :author_id
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges


  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def tests_by_level(level)
    tests.by_level(level)
  end

  def passing_test(test)
    passing_tests.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end


end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPES = { alert: 'warning', notice: 'info' }.freeze

  def this_year
    Time.current.year
  end

  def github_link(author_name, repository_name)
    "https://github.com/#{author_name}/#{repository_name}"
    link_to "Rails-First-App", "https://github.com/#{author_name}/#{repository_name}", target: :blank
  end

  def flash_messages
    flash.map do |type, message|
      content_tag :div, sanitize(message), class: flash_type(type), role: 'alert'
    end.join("\n").html_safe
  end

  private

  def flash_type(type)
    "alert alert-#{FLASH_TYPES[type.to_sym]}"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 1 => :easy, 2 => :medium, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
    case test.level
      when 1 then t('difficulty_level.easy')
      when 2 then t('difficulty_level.medium')
      when 3 then t('difficulty_level.hard')
      else t('difficulty_level.hero')
    end
  end

  def test_timer(test)
    test.timer ? t('.timer', time: test.timer) : t('.unlimited')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t('.header'), root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link active">
        <%= link_to 'Gists', admin_gists_path, class: 'navbar-link' %>
      </li>
      <li class="nav-item nav-link active">
        <%= link_to 'Badges', admin_badges_path, class: 'navbar-link' %>
      </li>
    </ul>
  </div>
  <span class="navbar-text">
    <%= t('.hello') %>,
    <b class="nav-admin user-email"><%= current_user.email %></b>
    <%= t('.guru') %>
    |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </span>
</div>
</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  <div>
    <h2><%= t('.header', count: resource.errors.count) %></h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}"   %>
<% end %>

app/views/shared/_footer.en.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <span class="text-muted">
      <%= this_year %> год - Tamchenko  Sergey<br>
      <%= github_link("spartakusQ", "Rails-First-App") %> Learning platform for testing.<br>
      <%= link_to "Educational project in an online-school Thinknetica", "https://thinknetica.com", target: :blank %>
    </span>
      <% if current_user %>
  <div class="float-right">
      <%= link_to 'Feedback', new_feedback_path, class: 'btn btn-outline-info' %>
  </div>
      <% end %>
</nav>

app/views/shared/_footer.html.erb
<p>
  <%= this_year %> год - Tamchenko  Sergey
</p>
 <p>
  <%= github_link("spartakusQ", "Rails-First-App") %> Учебная платформа для тестирования.
</p>
 <p>
  <%= link_to "Учебный проект в онлайн-школе Thinknetica", "https://thinknetica.com", target: :blank %>
</p>

app/views/shared/_footer.ru.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <span class="text-muted">
      <%= this_year %> год - Тамченко Сергей<br>
      <%= github_link("spartakusQ", "Rails-First-App") %> Учебная платформа для тестирования.<br>
      <%= link_to "Учебный проект в онлайн-школе Thinknetica", "https://thinknetica.com", target: :blank %>
  </span>
      <% if current_user %>
  <div class="float-right">
      <%= link_to 'Обратная связь', new_feedback_path, class: 'btn btn-outline-info' %>
  </div>
      <% end %>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

  <% if current_user && current_user.admin? %>
      <li class="nav-item active">
        <%= link_to t('admin.header.header'), admin_tests_path %>
        <%= link_to t('.badges'), badges_path %>
      </li>
  <% end %>

    </ul>
  </div>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= link_to 'Badge', admin_badges_path, class: 'btn btn-outline-info'  %>
      <% else %>
        <%= link_to 'Badge', badges_path, class: 'btn btn-outline-info'  %>
      <% end %>
      <%= t('.hello')%>,
      <b><%= current_user.email %></b>
      Guru |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.signup'), new_user_registration_path %>
      |
      <%= link_to t('.login'), new_user_session_path %>
    <% end %>
  </span>
</nav>